# Generated by Django 5.2.7 on 2025-12-01 16:41

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalWorkerDetail',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('TZS', 'TZS'), ('USD', 'USD')], default='TZS', max_length=10)),
                ('payment_period', models.CharField(blank=True, max_length=10, null=True)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('public_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nworker_jobcategory', to='Jobs.jobcategory')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normal_workers', to='Users.usersprofile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDetail',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('TZS', 'TZS'), ('USD', 'USD')], default='TZS', max_length=10)),
                ('payment_period', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('project', 'Per Project')], max_length=20)),
                ('linkedIn', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('gitHub', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='workerCv/')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('freelancer', 'Freelancer'), ('self_employed', 'Self-employed'), ('student', 'Student'), ('intern', 'Intern'), ('contract', 'Contract'), ('looking', 'Open to opportunities')], max_length=50)),
                ('experience_yrs', models.CharField(choices=[('0_1', '0–1 years'), ('1_2', '1–2 years'), ('2_3', '2–3 years'), ('3_5', '3–5 years'), ('5_7', '5–7 years'), ('7_10', '7–10 years'), ('10_plus', '10+ years')], max_length=20)),
                ('education_level', models.CharField(choices=[('none', 'No formal education'), ('primary', 'Primary School'), ('secondary', 'Secondary School / High School'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD / Doctorate')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_category', to='Jobs.jobcategory')),
                ('prof_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_detail', to='Users.usersprofile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalEducations',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.CharField(max_length=150)),
                ('end_year', models.CharField(blank=True, max_length=150)),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'High School / Secondary'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD / Doctorate')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_professional', to='Workers.professionaldetail')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_working', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_experience', to='Workers.professionaldetail')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalLanguages',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_professional', to='Workers.professionaldetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSkills',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_professional', to='Workers.professionaldetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
