# Generated by Django 5.2.7 on 2025-12-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalworkerdetail',
            name='availability',
            field=models.CharField(choices=[('WeekdaysOnly', 'Weekdays only'), ('WeekendsOnly', 'Weekends only'), ('Daily', 'Daily'), ('Immediate', 'Immediate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='normalworkerdetail',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=100),
        ),
        migrations.AlterField(
            model_name='normalworkerdetail',
            name='payment_period',
            field=models.CharField(choices=[('PerHour', 'Per hour'), ('PerDay', 'Per day'), ('PerWeek', 'Per week'), ('PerMonth', 'Per month'), ('Negotiable', 'Negotiable'), ('PerProject', 'Per project')], default='PerHour', max_length=10),
            preserve_default=False,
        ),
    ]
