# Generated by Django 5.2.7 on 2025-12-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0002_alter_normalworkerdetail_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaleducations',
            name='end_year',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
