# Generated by Django 5.2.7 on 2025-12-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0003_alter_professionaleducations_end_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionaldetail',
            old_name='currency',
            new_name='prof_currency',
        ),
        migrations.RenameField(
            model_name='professionaldetail',
            old_name='payment_period',
            new_name='prof_payment_period',
        ),
        migrations.RenameField(
            model_name='professionaldetail',
            old_name='salary',
            new_name='prof_salary',
        ),
    ]
