# Generated by Django 5.2.7 on 2025-12-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0004_rename_currency_professionaldetail_prof_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionaldetail',
            old_name='description',
            new_name='prof_description',
        ),
    ]
