# Generated by Django 5.2.7 on 2025-12-01 16:41

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('industry', models.CharField(max_length=200)),
                ('employees_size', models.CharField(choices=[('self_employed', 'Self Employed'), ('1-10', '1–10 employees'), ('11-50', '11–50 employees'), ('51-200', '51–200 employees'), ('201-500', '201–500 employees'), ('501-1000', '501–1,000 employees'), ('1001-5000', '1,001–5,000 employees'), ('5001-10000', '5,001–10,000 employees'), ('10000+', '10,000+ employees')], max_length=100)),
                ('year_founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=250)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('COMPANY', 'Company jobs'), ('INDIVIDUAL', 'Individual / Street job')], max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260)),
                ('code', models.CharField(editable=False, max_length=60, unique=True)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('remote', 'Remote')], max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('none', 'No Education Required'), ('primary', 'Primary Education'), ('secondary', 'Secondary Education / High School'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor’s Degree'), ('master', 'Master’s Degree'), ('phd', 'Doctorate (PhD)')], max_length=100, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('no_experience', 'No Experience Required'), ('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive / Director')], max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('any', 'Any (Not Specified)'), ('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_visible', models.BooleanField(default=True)),
                ('currency', models.CharField(choices=[('TZS', 'TZS'), ('USD', 'USD')], default='TZS', max_length=10)),
                ('payment_period', models.CharField(blank=True, choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month'), ('annually', 'Per Year'), ('piecework', 'Per Task / Piece')], max_length=20, null=True)),
                ('positions_needed', models.PositiveSmallIntegerField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('job_summary', models.TextField(blank=True, null=True)),
                ('duties', models.TextField(blank=True, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('apply_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('apply_website', models.URLField(blank=True, null=True)),
                ('apply_in_app', models.BooleanField(default=False)),
                ('apply_whatsapp', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('applied', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sw_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_type', models.CharField(choices=[('professional', 'Professional Jobs'), ('informal', 'Casual / Daily Jobs')], max_length=22)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
