# Generated by Django 5.2.7 on 2025-12-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0001_initial'),
        ('Locations', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_company', to='Users.usersprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_company', to='Jobs.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.district'),
        ),
        migrations.AddField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_jobs', to='Users.usersprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.region'),
        ),
        migrations.AddField(
            model_name='job',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.ward'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_job', to='Jobs.jobcategory'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_company'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category'], name='Jobs_job_categor_77842b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['region', 'district'], name='Jobs_job_region__abc387_idx'),
        ),
    ]
