# Generated by Django 5.2.7 on 2025-12-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
