# Generated by Django 5.2.7 on 2025-12-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_alter_job_apply_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('no_experience', 'No Experience Required'), ('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior Level (5+ years)'), ('executive', 'Executive / Director')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(blank=True, choices=[('any', 'Any (Not Preference)'), ('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
    ]
