# Generated by Django 5.2.7 on 2025-12-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_alter_job_apply_in_app_alter_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_period',
            field=models.CharField(blank=True, choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month'), ('annually', 'Per Year'), ('piecework', 'Per Task')], max_length=20, null=True),
        ),
    ]
