# Generated by Django 5.2.7 on 2025-12-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_alter_job_payment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, unique=True),
        ),
    ]
