# Generated by Django 5.2.7 on 2025-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_whatsapp',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
