# Generated by Django 5.2.7 on 2025-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_alter_job_apply_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_type',
            field=models.CharField(choices=[('COMPANY', 'Company job'), ('INDIVIDUAL', 'Individual job')], max_length=20),
        ),
    ]
