# Generated by Django 5.2.7 on 2025-12-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_alter_job_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual')], max_length=20),
        ),
    ]
