# Generated by Django 5.2.7 on 2025-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_method',
            field=models.CharField(choices=[('IN_PLATFORM', 'Applied on this platform'), ('WEBSITE', 'Applied on company website'), ('EMAIL', 'Applied by email'), ('WHATSAPP', 'Applied via WhatsApp')], default='IN_PLATFORM', max_length=30),
            preserve_default=False,
        ),
    ]
