# Generated by Django 5.2.7 on 2025-12-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobDetails', '0002_jobapplication_application_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_method',
            field=models.CharField(choices=[('IN_PLATFORM', 'Applied on this platform'), ('WEBSITE', 'Applied via company website'), ('EMAIL', 'Applied via email'), ('WHATSAPP', 'Applied via WhatsApp')], max_length=30),
        ),
    ]
